name: Release

on:
  schedule:
    - cron: "0 0 * * 1"  # Runs every Monday at midnight UTC
  push:
    branches:
      - arm64
  workflow_dispatch:  # Allows manual triggering

jobs:
  Kitty:
    runs-on: ubuntu-22.04  # Using ARM64-compatible Ubuntu 22.04 runner

    strategy:
      matrix:
        version: ['3.8']

    steps:
      - uses: actions/checkout@v2

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget tar libfuse2  # Install wget, tar, and libfuse2 for AppImage support
          sudo apt-get install -y qemu-user-static  # Install QEMU for ARM64 emulation

      - name: Set up Docker for ARM64 emulation
        run: |
          docker buildx create --use  # Enable multi-architecture build support

      - name: Build Kitty AppImage
        run: |
          # Run the appimagetool for ARM64 in Docker
          docker run --rm -v $(pwd):/mnt ghcr.io/appimage/appimagetool:latest /mnt/AppDir -n -u "https://github.com/lucasscvvieira/kitty-appimage/releases/download/stable/Kitty*.AppImage.zsync" /mnt/Kitty--arm64.AppImage

      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: Kitty Stable AppImage Builds
          automatic_release_tag: stable
          prerelease: false
          draft: false
          files: ./kitty/dist/Kitty-*-arm64.AppImage*  # Change architecture from x86_64 to arm64
          repo_token: ${{ secrets.GITHUB_TOKEN }}
