name: Release

on:
  schedule:
    - cron: "0 0 * * 1"  # Runs every Monday at midnight UTC
  push:
    branches:
      - arm64
  workflow_dispatch:  # Allows manual triggering

jobs:
  Kitty:
    runs-on: ubuntu-22.04  # Set to ARM64 support using Ubuntu 22.04

    strategy:
      matrix:
        version: ['3.8']

    steps:
      - uses: actions/checkout@v2

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget tar libfuse2  # Install wget, tar, and libfuse2 for AppImage support

      - name: Build Kitty AppImage
        run: ./build.sh

      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: Kitty Stable AppImage Builds
          automatic_release_tag: stable
          prerelease: false
          draft: false
          files: ./kitty/dist/Kitty-*-arm64.AppImage*  # Change architecture from x86_64 to arm64
          repo_token: ${{ secrets.GITHUB_TOKEN }}
