name: Build for ARM64 Linux

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04  # GitHub Actions runner based on Ubuntu 22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU for ARM64 emulation (if needed)
        uses: docker/setup-buildx-action@v2
        with:
          use-qemu: true

      - name: Set up ARM64 architecture for Docker build
        run: |
          docker buildx create --use
          docker buildx build --platform linux/arm64,linux/amd64 -t your-image-name .

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Build project
        run: |
          make # or any other build command for your project

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: arm64-build-artifact
          path: ./build/output-directory  # Replace with actual path
